'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MassarelliLoadSheetApp.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property MassarelliIcon_LoadSheet4848() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("MassarelliIcon_LoadSheet4848", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ibillorship.
        '''</summary>
        Friend ReadOnly Property PARAM_billorship() As String
            Get
                Return ResourceManager.GetString("PARAM_billorship", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCreateDate.
        '''</summary>
        Friend ReadOnly Property Param_iCreateDate() As String
            Get
                Return ResourceManager.GetString("Param_iCreateDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iFieldName.
        '''</summary>
        Friend ReadOnly Property Param_iFieldName() As String
            Get
                Return ResourceManager.GetString("Param_iFieldName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLoadSheetNo.
        '''</summary>
        Friend ReadOnly Property Param_iLoadSheetNo() As String
            Get
                Return ResourceManager.GetString("Param_iLoadSheetNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iLocDesc.
        '''</summary>
        Friend ReadOnly Property Param_iLocDesc() As String
            Get
                Return ResourceManager.GetString("Param_iLocDesc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ioNewKey.
        '''</summary>
        Friend ReadOnly Property Param_ioNewKey() As String
            Get
                Return ResourceManager.GetString("Param_ioNewKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iOrdNo.
        '''</summary>
        Friend ReadOnly Property Param_iOrdNo() As String
            Get
                Return ResourceManager.GetString("Param_iOrdNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPalletQty.
        '''</summary>
        Friend ReadOnly Property Param_iPalletQty() As String
            Get
                Return ResourceManager.GetString("Param_iPalletQty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iProNumber.
        '''</summary>
        Friend ReadOnly Property Param_iProNumber() As String
            Get
                Return ResourceManager.GetString("Param_iProNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSearchOrdNo.
        '''</summary>
        Friend ReadOnly Property Param_iSearchOrdNo() As String
            Get
                Return ResourceManager.GetString("Param_iSearchOrdNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSequence.
        '''</summary>
        Friend ReadOnly Property Param_iSequence() As String
            Get
                Return ResourceManager.GetString("Param_iSequence", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iShipToAddr.
        '''</summary>
        Friend ReadOnly Property Param_iShipToAddr() As String
            Get
                Return ResourceManager.GetString("Param_iShipToAddr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iShipToName.
        '''</summary>
        Friend ReadOnly Property Param_iShipToName() As String
            Get
                Return ResourceManager.GetString("Param_iShipToName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iShipVia.
        '''</summary>
        Friend ReadOnly Property Param_iShipVia() As String
            Get
                Return ResourceManager.GetString("Param_iShipVia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iState.
        '''</summary>
        Friend ReadOnly Property Param_iState() As String
            Get
                Return ResourceManager.GetString("Param_iState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iTableName.
        '''</summary>
        Friend ReadOnly Property Param_iTableName() As String
            Get
                Return ResourceManager.GetString("Param_iTableName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iord_no.
        '''</summary>
        Friend ReadOnly Property PARAM_ord_no() As String
            Get
                Return ResourceManager.GetString("PARAM_ord_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spGetNextNo_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spGetNextNo_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spGetNextNo_MAS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spOEGetOrdHdrBillShipCSZ.
        '''</summary>
        Friend ReadOnly Property SP_spOEGetOrdHdrBillShipCSZ() As String
            Get
                Return ResourceManager.GetString("SP_spOEGetOrdHdrBillShipCSZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spOESaveLoadSheet_MAS.
        '''</summary>
        Friend ReadOnly Property SP_spOESaveLoadSheet_MAS() As String
            Get
                Return ResourceManager.GetString("SP_spOESaveLoadSheet_MAS", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
